### ISSUE TITLE
When alphanumeric key is used it can not be retrieved from PHP

### ISSUE THREAD

**Issue by bmhaskar** [3rd-Eden/node-memcached#175]
I am setting a key using following code 
```nodejs
var memcached = new Memcached(str.split(","),options);
var key ="abc1";
memcached.on('failure', function( details ){ sys.error( "Server " + details.server + "went down due to: " + details.messages.join( '' ) ) });
 memcached.set(key,'bharat',60*60*24*30,function (error, result) {
                console.log(error);
                console.log(result);
                console.log("herer");
        })

```

When I try to retrieve the same key i.e "abc1" from PHP   it doesn't return any value. 

The code works fine if I use key as "abc".

**Comment by rcoup** [comment]
Is this with multiple hosts? if so, is your PHP client set to `ketama_weighted=true` and `hash=md5` as described in [Compatibility](https://github.com/3rd-Eden/node-memcached#compatibility)?

Otherwise, can you get a tcpdump of the PHP client GET/SET and the node-memcached client GET/SET? (Using something like `sudo tcpdump -i eth0 -s 65535 -A -ttt port 11211`)

**Comment by bmhaskar** [comment]
Yes it is multiple memcached  hosts setup. It was issue at PHP end the algorithm to determine host was flawed, not an issue with node-memcached.
